config/routes.rb
Promise::Application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api do
    devise_scope :user do
      post "users/sign_up", to: "users/registrations#create"
      post "users/social_sign_up", to: "users/registrations#social_create"
      post "users/sign_in", to: "users/sessions#create"
      post "users/sign_out", to: "users/sessions#destroy"
    end

    get "district/sidos"
    get "district/sidos/:id/sigungus", to: "district#sigungus"
    get "district/search", to: "district#search"

    get "elections", to: "elections#index"
    get "elections/:id/politicians", to: "elections#politicians"

    get "manifestos/daily"
    get "manifestos/:id", to: "manifestos#show"
    post "manifestos/:id", to: "manifestos#show"
    get "manifestos/politician/:id", to: "manifestos#politician"

    get "parties", to: "parties#index"
    get "parties/:id/politicians", to: "parties#politicians"

    get "politicians/search"
    get "politicians/my_district/:id", to: "politicians#my_district"
    get "politicians/my_location", to: "politicians#my_location"
    get "politicians/:id", to: "politicians#show"

    post "ratings/update"
    post "ratings/destroy"

    get "replies/manifesto/:id", to: "replies#manifesto"
    get "replies/politician/:id", to: "replies#politician"
    get "replies/:type/:id", to: "replies#index"

    post "replies/create"
    post "replies/destroy"

    post "reply_evaluations/create"
    post "reply_evaluations/update"
    post "reply_evaluations/destroy"

    post "reply_reports/create"

    get "versus", to: "versus#index"
    get "versus/:id", to: "versus#show"
    post "versus/:id/vote", to: "versus#vote"

    get "issues", to: "issues#index"
    get "issues/:id", to: "issues#show"
  end

  resources :parties
  resources :positions
  resources :manifestos
  resources :politicians
  resources :ratings
  resources :replies
  resources :reply_evaluations

  match '/ios', :to => redirect('/00Promise.ipa')

end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :district, :enabled, :name, :type_code, :type_name
  has_one :winner # 향후 current = true 조건 추가
  has_one :politician, through: :winner # 향후 current = true 조건 추가

end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type_name %><br />
    <%= f.text_field :type_name %>
  </div>
  <div class="field">
    <%= f.label :type_code %><br />
    <%= f.number_field :type_code %>
  </div>
  <div class="field">
    <%= f.label :district %><br />
    <%= f.text_field :district %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type name</th>
    <th>Type code</th>
    <th>District</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @positions.each do |position| %>
  <tr>
    <td><%= position.name %></td>
    <td><%= position.type_name %></td>
    <td><%= position.type_code %></td>
    <td><%= position.district %></td>
    <td><%= link_to 'Show', position %></td>
    <td><%= link_to 'Edit', edit_position_path(position) %></td>
    <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position', new_position_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @position.name %>
</p>

<p>
  <b>Type name:</b>
  <%= @position.type_name %>
</p>

<p>
  <b>Type code:</b>
  <%= @position.type_code %>
</p>

<p>
  <b>District:</b>
  <%= @position.district %>
</p>


<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>